# This workflow gets app version from package.json and uses it as release tag and title with.
# This workflow makes main branch as a workspace with (actions/checkout@v3)
# This workflow adds CHANGELOG.md file to downloadable files.
# This workflow gets changelog info with (coditory/changelog-parser@v1)
# This workflow automatically creates release with version tag and latest changelog version description on main push with (softprops/action-gh-release@v1).

name: 🚀 Publish Nearby Locations Release

# Controls when the workflow will run
on:
  push:
    branches:
      - "main"
# Controls what the workflow does
jobs:
  build:
    name: ⚙️ Create Release Automatically
    runs-on: ubuntu-latest
    steps:


      - name: 🔃 Checkout branch "main"
        uses: actions/checkout@v3
        with:
          ref: 'main'


      - name: 🔖 Get App Version
        id: version
        run: |
          TAG_VERSION=$(cat package.json | grep version | awk '{ print $2}' | sed 's/[",]//g')
          echo "$TAG_VERSION"
          echo "::set-output name=tag_name::v${TAG_VERSION}"
          echo "::set-output name=release_name::v${TAG_VERSION}"


      - name: 📢 Prepare Release ChangeLog
        id: changelog
        uses: coditory/changelog-parser@v1


      - name: 🛎️ Create Release + TAG
        id: release-snapshot
        uses: softprops/action-gh-release@v1
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{ steps.version.outputs.tag_name }}
          name: ${{ steps.version.outputs.release_name }}
          body: ${{ steps.changelog.outputs.description }}
          body_path: ${{ steps.release_notes.outputs.path }}
          target_commitish: ${{ github.sha }}
          draft: false
          prerelease: false
          generate_release_notes: true

          files: |
            CHANGELOG.md